### PR TITLE
Update tamil.toml

### PR DESCRIPTION
**Pull request by karthikraman**

### CODE REVIEW

**Comment by vvasuki** [comment]
why does transliteration of devanAgati anusvAra to m instead of anusvAra by
default make sense?

**Comment by karthikraman** [comment]
There is no anusvAra in Tamil (anunAsikas are only used), and this renders a dot on characters, which generally denotes a halant-type virama.

**Comment by vvasuki** [comment]
அஂ is अँ  or is it अं? The first character in https://en.wikipedia.org/wiki/Tamil_(Unicode_block) is named "tamil anusvAra". Does the name not match popular usage?

**Comment by karthikraman** [comment]
I guess no one knows what அஂ is :-) अं is written only as அம்... संस्कृतम् is written as ஸம்ஸ்க்ருʼதம். Perhaps @jamadagni could shed light on use of ஂ

**Comment by jamadagni** [comment]
https://unicode.org/L2/L2012/12018-tamil-anusvara-depr.pdf

**Comment by vvasuki** [comment]
Thanks to both of you!

**Pull request merged**
