### PR TITLE
Update tamil_extended.json

### PR DESCRIPTION
**Pull request by karthikraman**
Update R RR L LL

### CODE REVIEW

**Comment by vvasuki** [comment]
You seem to 've misunderstood tamil_extended.json - it's intended to extend tamiL character set with grantha where the former lacks a character - whereas you try to cope with quote mark repurposed as a diacritic.

Perhaps you want to use tamil_superscripted?

**Comment by karthikraman** [comment]
Then we need to enter grantha characters? Since the map was empty, I thought these could be used. But sure, grantha characters can be added too.

**Comment by vvasuki** [comment]
The grantha characters were already there, but you replaced them in this CL - 
image

**Comment by karthikraman** [comment]
oops, sorry!

**Pull request closed without merging**
